import { Inter } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/ui/dashboard/header";
import { Sidebar } from "@/components/ui/dashboard/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { OrderProvider } from "@/context/OrderContext";
import { NewOrder } from "./newOrder";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "tacoza Seller",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <OrderProvider>
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <Sidebar />
            <div className="flex flex-col max-h-screen overflow-hidden">
              <Header />
              {children}
              <Toaster />
            </div>
          </div>
          <NewOrder />
        </OrderProvider>
      </body>
    </html>
  );
}
